// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookingSystem.Data;

#nullable disable

namespace bookingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214195820_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("bookingSystem.Models.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(180),
                            EndDate = new DateTime(2025, 12, 27, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(6544),
                            ResourceId = 9,
                            StartDate = new DateTime(2025, 12, 23, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(6544),
                            Status = "Completed",
                            UserId = 8
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(600),
                            EndDate = new DateTime(2025, 12, 5, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(590),
                            ResourceId = 2,
                            StartDate = new DateTime(2025, 12, 4, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(590),
                            Status = "InProgress",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(603),
                            EndDate = new DateTime(2025, 12, 24, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(601),
                            ResourceId = 5,
                            StartDate = new DateTime(2025, 12, 22, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(601),
                            Status = "Requested",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(605),
                            EndDate = new DateTime(2025, 12, 23, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(603),
                            ResourceId = 1,
                            StartDate = new DateTime(2025, 12, 20, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(603),
                            Status = "Expired",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(607),
                            EndDate = new DateTime(2025, 12, 8, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(605),
                            ResourceId = 1,
                            StartDate = new DateTime(2025, 12, 7, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(605),
                            Status = "Completed",
                            UserId = 8
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(613),
                            EndDate = new DateTime(2025, 12, 19, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(612),
                            ResourceId = 6,
                            StartDate = new DateTime(2025, 12, 16, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(612),
                            Status = "Confirmed",
                            UserId = 9
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(615),
                            EndDate = new DateTime(2025, 12, 19, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(614),
                            ResourceId = 1,
                            StartDate = new DateTime(2025, 12, 15, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(614),
                            Status = "InProgress",
                            UserId = 8
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(618),
                            EndDate = new DateTime(2025, 12, 9, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(616),
                            ResourceId = 5,
                            StartDate = new DateTime(2025, 12, 5, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(616),
                            Status = "NoShow",
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(620),
                            EndDate = new DateTime(2025, 12, 26, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(618),
                            ResourceId = 2,
                            StartDate = new DateTime(2025, 12, 22, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(618),
                            Status = "Completed",
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(623),
                            EndDate = new DateTime(2025, 12, 7, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(621),
                            ResourceId = 2,
                            StartDate = new DateTime(2025, 12, 6, 19, 58, 19, 642, DateTimeKind.Utc).AddTicks(621),
                            Status = "Rescheduled",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("bookingSystem.Models.Resources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(1362),
                            Description = "Auto generated resource number 1",
                            IsActive = true,
                            Name = "Resource 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(1812),
                            Description = "Auto generated resource number 2",
                            IsActive = true,
                            Name = "Resource 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(1815),
                            Description = "Auto generated resource number 3",
                            IsActive = true,
                            Name = "Resource 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(1818),
                            Description = "Auto generated resource number 4",
                            IsActive = true,
                            Name = "Resource 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(1821),
                            Description = "Auto generated resource number 5",
                            IsActive = true,
                            Name = "Resource 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(1827),
                            Description = "Auto generated resource number 6",
                            IsActive = false,
                            Name = "Resource 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(1829),
                            Description = "Auto generated resource number 7",
                            IsActive = true,
                            Name = "Resource 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(1831),
                            Description = "Auto generated resource number 8",
                            IsActive = false,
                            Name = "Resource 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(1833),
                            Description = "Auto generated resource number 9",
                            IsActive = false,
                            Name = "Resource 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 641, DateTimeKind.Utc).AddTicks(1841),
                            Description = "Auto generated resource number 10",
                            IsActive = true,
                            Name = "Resource 10"
                        });
                });

            modelBuilder.Entity("bookingSystem.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 638, DateTimeKind.Utc).AddTicks(1391),
                            Email = "user1@booking.com",
                            PasswordHash = "hashed_password_1",
                            Role = "user"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 638, DateTimeKind.Utc).AddTicks(2060),
                            Email = "user2@booking.com",
                            PasswordHash = "hashed_password_2",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 638, DateTimeKind.Utc).AddTicks(2064),
                            Email = "user3@booking.com",
                            PasswordHash = "hashed_password_3",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 638, DateTimeKind.Utc).AddTicks(2068),
                            Email = "user4@booking.com",
                            PasswordHash = "hashed_password_4",
                            Role = "user"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 638, DateTimeKind.Utc).AddTicks(2070),
                            Email = "user5@booking.com",
                            PasswordHash = "hashed_password_5",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 638, DateTimeKind.Utc).AddTicks(2083),
                            Email = "user6@booking.com",
                            PasswordHash = "hashed_password_6",
                            Role = "user"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 638, DateTimeKind.Utc).AddTicks(2086),
                            Email = "user7@booking.com",
                            PasswordHash = "hashed_password_7",
                            Role = "user"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 638, DateTimeKind.Utc).AddTicks(2088),
                            Email = "user8@booking.com",
                            PasswordHash = "hashed_password_8",
                            Role = "user"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 638, DateTimeKind.Utc).AddTicks(2091),
                            Email = "user9@booking.com",
                            PasswordHash = "hashed_password_9",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 14, 19, 58, 19, 638, DateTimeKind.Utc).AddTicks(2099),
                            Email = "user10@booking.com",
                            PasswordHash = "hashed_password_10",
                            Role = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
